<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-07-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
=======
# Generated by Django 4.2.13 on 2024-07-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
>>>>>>> 3688f8f (signals)
